title: Owen Trueblood
author: Owen Trueblood
description: >
  As an artist I create and explore emergent phenomena in complex
  systems. As an engineer I develop tools for applying creativity.
url: https://owentrueblood.com

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM

permalink: /blog/:year/:month/:day/:title/

feed:
  path: blog/feed.xml

plugins:
  - jekyll-feed

